[package]
name = "uniswap-toolbox"
version = "0.1.0"
edition = "2021"

[dependencies]
uniswap-math = { path = "uniswap-math" }

[workspace]
members = [
    "uniswap-math",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
